# Use the official Alpine image as a parent image
FROM alpine:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /app
COPY . .

# Run a simple command to display Hello World
CMD ["echo", "Hello, Docker 🙋‍♂️"]